Iter5
PoorMercymain/urlshrt pull request #5
Opened 2023-05-06 17:47 UTC by PoorMercymain

2023-05-09 08:30 UTC, arttet requested changes
Good job!

2023-05-09 08:30 UTC, arttet commented on cmd/shortener/main.go
> +	HTTPEnv, HTTPSet := os.LookupEnv("SERVER_ADDRESS")
You might consider changing "HTTPEnv" to "httpEnv" and "ShortEnv" to "shortEnv"

2023-05-09 08:30 UTC, arttet commented on internal/domain/db.go
> +	f, err := os.Open(db.location)
Please apply `go fmt`

2023-05-09 08:30 UTC, arttet commented on internal/domain/db.go
> +	f, err := os.OpenFile(db.location, os.O_APPEND|os.O_WRONLY|os.O_CREATE, 0600)
Why have you decided to save data into files?

2023-05-09 08:30 UTC, arttet commented on internal/domain/db.go
> +		f.WriteString(str + "\n")
Please don't use `+`. You can use two functions.

2023-05-09 08:30 UTC, arttet commented on internal/domain/url.go
> +	return u.Original + " " + u.Shortened
Please use `fmt.Sprintf`

2023-05-09 08:30 UTC, arttet commented on internal/domain/url.go
> +	w.WriteHeader(400)
This is a magic number.

2023-05-09 08:30 UTC, arttet commented on internal/domain/url.go
> +			w.WriteHeader(307)
This is a magic number.

2023-05-09 08:30 UTC, arttet commented on internal/domain/url.go
> +	length := 7
This is a magic number.

2023-05-09 08:30 UTC, arttet commented on internal/domain/url.go
> +	var urlStrArr []string
It would be better if you use `make`

2023-05-10 10:46 UTC, PoorMercymain commented on internal/domain/db.go
> +	f, err := os.OpenFile(db.location, os.O_APPEND|os.O_WRONLY|os.O_CREATE, 0600)
I thought that it might be a simple way to store data about urls between launches (even though now I don't think so)

2023-05-12 19:33 UTC, arttet requested changes

2023-05-12 19:33 UTC, arttet commented on cmd/shortener/main.go
> +	urls := make([]domain.URL, 0)
It would be better if you use `1`

2023-05-12 19:33 UTC, arttet commented on internal/config/config.go
> +func (a *AddrWithCheck) Set(s string) error {
Nit: it is redundant or `Set` is not clear.

2023-05-12 19:33 UTC, arttet commented on internal/domain/db.go
> +type DB struct {
Nit:: `Database`

2023-05-12 19:33 UTC, arttet commented on internal/domain/db.go
> +		u := URL{Original: strings.Split(scanner.Text(), " ")[0], Shortened: strings.Split(scanner.Text(), " ")[1]}
It's not safety. It would be better if you split this code.

2023-05-12 19:33 UTC, arttet commented on internal/domain/db.go
> +		f.WriteString("\n")
`WriteByte('a')`

2023-05-12 19:33 UTC, arttet commented on internal/domain/url.go
> +func (u URL) String() string {
Why don't you use a pointer?

2023-05-12 19:33 UTC, arttet commented on internal/domain/url.go
> +		randStrBytes[i] = byte(65 + symbolCode)
This is a magic number. You can use `a`.

2023-05-12 19:33 UTC, arttet commented on internal/domain/url.go
> +		symbolCode := rand.Intn(53)
This is a magic number.

2023-05-16 19:25 UTC, arttet approved these changes

2023-05-16 19:25 UTC, arttet commented on internal/domain/url.go
> +	urlStrArr := make([]string, 0)
```
urlStrArr := []string{ u.String() }
```

2023-05-16 19:25 UTC, arttet commented on internal/domain/url.go
> +	db := NewDB("txt", "testTxtDB.txt")
It should be in another package.

2023-05-16 19:25 UTC, arttet commented on internal/domain/url.go
> +	rand.Seed(time.Now().Unix())
P.S. https://cs.opensource.google/go/go/+/go1.20.4:src/math/rand/rand.go;l=324

https://pkg.go.dev/math/rand#Seed

2023-05-20 14:02 UTC, merged